spring:
  datasource:
    url: jdbc:mysql://localhost:3307/maybankdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: maybank
    password: maybank123
    # driver-class-name is optional in Boot 3 (autodetected), but you can pin it:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update          # dev/demo; use 'validate' in prod with migrations
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # Hibernate 6 dialect name

  batch:
    jdbc:
      initialize-schema: always  # create Spring Batch metadata tables for MySQL

# Optional: show SQL in dev
logging:
  level:
    org.hibernate.SQL: debug


#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/maybankdb
#    username: maybank
#    password: maybank
#  jpa:
#    hibernate:
#      ddl-auto: update   # for demo; use 'validate' in prod
#    open-in-view: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#  batch:
#    jdbc:
#      initialize-schema: always  # create Spring Batch metadata tables in Postgres
#    job:
#        enabled: true              # enable Spring Batch jobs
## If you used Spring Batch, ensure the job actually runs:
## spring.batch.job.enabled: true                     # default true
#logging:
#  level:
#    org.springframework.batch: INFO
